dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod a+x ./gradlew
before_deploy:
- openssl aes-256-cbc -K $encrypted_0a955d82cc5c_key -iv $encrypted_0a955d82cc5c_iv
  -in .travis/keys.tar.enc -out .travis/keys.tar -d
- tar xvf .travis/keys.tar -C .travis
script:
- "./gradlew test"
branches:
  only:
  - master
deploy:
  skip_cleanup: true # needed so that no "git stash" is executed, which would then remove the pgp keys extracted in before_deploy
  provider: script
  script: "./gradlew publishToNexus closeAndReleaseRepository --info --stacktrace"
notifications:
  slack:
    secure: irWJp56rtNMvlTZbb4SP6fUyn61VGQPd7lj0eumm/U8qplcbHhb/CkYaRAuBe6CucWckg2IurFUIVwinqWrWk3pFlWCqzULCgVpRpQ5cTDYtWHs5n7xEaK7/PdcRJZXE3m6hZLPCXmuh1NkXHaUEMlYb81SqfuIinq/xevFbaYy9A39UQ6QIXlvn0ea+H6zT1bVGSx5ZlcHzqBGSiQHbK6YKYEOiCHD0TAV6H08JaS8h3efjWVyyYz667mAKBmYVJq2CewSKKCCLubqjm1KSRSsWn0+Fjoj5FuhVkKs4cyN3a1551SJY9jL8GdZ2utM0XjRKEkccJkfcBGMZujaMKKQPImPVwIjFTn572WWw7oBrVTqfKcBagXwzLTKVlmL1EmYYkDWjOIyfyoWf0bmOP/eGcYRLfI2uC6L97APfD+jvpbqX3NPvex0ipBrdLv3hMXgrmBI+1XyenxL98uoG12pd25DwUAIg9k+gmT2CUQJ9vCs/7nDJj7YJ0tk6a1ZFEP8sNaLVXhKpNrj//BEsoGk/mcZ3Yh3XHKdOTTCO0+nY5OGOe57vQQAZsBe0FK0MbXH3zAW5FiCAY5wCERHZ1N6ZKCuBwNTBuy3+0AOsBO6fofzZjZB4GgL8SZolny3LW8uGdDWZFcBIIiLI6VY4S6+mnRYn5F/h+3mcqbWzlsc=
env:
  global:
    secure: nDa16Deu7mSK8DSaZHI20Zpm2ZUWIfmIvXwlnExnCEJkvasfz6duTcq/l0XsNgRdQtTDrMwYKm5PPAsNrtakNc9mbP0U4a+8gdIKPVOMbr4QT7jRkfDt9dn+UvbRxSHeDTe0Dgbtsg8SxShyUdzBxdne0c6XTtePNUDVxJUTPt19HAUxYLOWzR6A2nIyNyYvRMoa57sipOCVmXpSSu3yrMdjT0c0IXWp14gyydhl/s3U8qE5iKPr1lr20BNTXq1G12C4mWrX7JtnwOg/Ms/Ol5537A794yGMk7iVdyqBp63o0tz+Mo2PDnZmg5BpPSHGDF9TH92ew63xS/BSYveAkSWy6Uaa5YU5AC19Tyi8a9w4sRy6zNlKMTdH90/JuVn53EhH8ZzeYYBJRoCCvJFatCcU2J8FXFO360bEkn16f5woYH1dSHxnQVdnoQRb5gDr33OAVWBFwAVja2mPkcHsm5VWNVA4t3tjoQ0iFmMdO92wlX/9Hdfei3OCs2Cs+XGLuHOgkO78M6jPZWs063ugO5kzbLHqEWEKsDzgc/r8N7WZNM1OAXs2zCsb0e9RUjPHYM1KWWEwfb7sg/omNpwX9eMql1GIFaGVKS826k54l2fDFlLfwvLdIdHEyiiYQGAzViSeuYgY5hmvh0yJvssx5KTsqUo9SxL1F3OktapNUgQ=
