language: java
jdk:
- oraclejdk8
before_install:
- chmod a+x ./gradlew
before_deploy:
- openssl aes-256-cbc -K $encrypted_0a955d82cc5c_key -iv $encrypted_0a955d82cc5c_iv
  -in keys.tar.enc -out .travis/keys.tar -d
- tar xvf .travis/keys.tar
script:
- "./gradlew test"
branches:
  only:
  - master
notifications:
  slack:
    secure: kQaTYS7GluRh+oQY5gK1wl7V0j/Sn4NSlC31fSm8A/Qz2bBdP+3L7+757K2kXzqUaKl2muyUpMKvsvzZ+tU3Zjx5w2qnyvBU2vsEysae8h2VmIgp1Q+N+cORWCfLtEmv64VTf3/rMs8DyA04zREfVPtqIUMHh0Ul0yYEyPMWRstY2U8aMZglHYnv1/eHdCDnLHzPuUBOvzN3EeZY80PO/r0lq7+2NY5f3afoCiEPXUzzuOy28Dd2oyEfGGf65TRe+BNU9vSAn49WwJLH/U22c3M60fbiwuA4E3JLMbyeP0JUnGGZ8lpFqm8e9xvR4/x9J7f974ri1pGlJsLD1Vo55ar7UtNhrqyJeQoxwncfpHEpo+VS4COc+PFU8PzZkVZAmZNlO73HToq1xLMZqQ+S2Kk39u6FAjNopIeGEb6BCy46lSme0vnQ5WRxteEIeW9T8oOEJhqO7ztmyKdO++zBcQw+XoozTiPXxsecJTCi28O+7OBoohGeVgdro/QebX5HZrNJ388FDO3slzTudR6QsJrcfM8QhhGadpUKUVm1P6BNwqGlpb3KvRySpbuGz7xlbL3jF6zSBgsaqH7oEurZBBOluHobTUksD/5W4ibl+KKu8APeENcwWjdmPVa5i7rOCFvzmoEKcFMqz+tuP+WKD3REuVit040xlTAjURXN0Lc=
env:
  global:
    secure: nDa16Deu7mSK8DSaZHI20Zpm2ZUWIfmIvXwlnExnCEJkvasfz6duTcq/l0XsNgRdQtTDrMwYKm5PPAsNrtakNc9mbP0U4a+8gdIKPVOMbr4QT7jRkfDt9dn+UvbRxSHeDTe0Dgbtsg8SxShyUdzBxdne0c6XTtePNUDVxJUTPt19HAUxYLOWzR6A2nIyNyYvRMoa57sipOCVmXpSSu3yrMdjT0c0IXWp14gyydhl/s3U8qE5iKPr1lr20BNTXq1G12C4mWrX7JtnwOg/Ms/Ol5537A794yGMk7iVdyqBp63o0tz+Mo2PDnZmg5BpPSHGDF9TH92ew63xS/BSYveAkSWy6Uaa5YU5AC19Tyi8a9w4sRy6zNlKMTdH90/JuVn53EhH8ZzeYYBJRoCCvJFatCcU2J8FXFO360bEkn16f5woYH1dSHxnQVdnoQRb5gDr33OAVWBFwAVja2mPkcHsm5VWNVA4t3tjoQ0iFmMdO92wlX/9Hdfei3OCs2Cs+XGLuHOgkO78M6jPZWs063ugO5kzbLHqEWEKsDzgc/r8N7WZNM1OAXs2zCsb0e9RUjPHYM1KWWEwfb7sg/omNpwX9eMql1GIFaGVKS826k54l2fDFlLfwvLdIdHEyiiYQGAzViSeuYgY5hmvh0yJvssx5KTsqUo9SxL1F3OktapNUgQ=
