dist: trusty
language: java
jdk:
  - oraclejdk8

before_install:
  # ensure gradlew has proper permission
  - chmod a+x ./gradlew

before_deploy:
  - openssl aes-256-cbc -K $encrypted_0a955d82cc5c_key -iv $encrypted_0a955d82cc5c_iv
    -in .travis/keys.tar.enc -out .travis/keys.tar -d
  - tar xvf .travis/keys.tar -C .travis

script:
  - ./gradlew test

branches:
  only:
    - master

deploy:
  skip_cleanup: true # needed so that no "git stash" is executed, which would then remove the pgp keys extracted in before_deploy
  provider: script
  script: ./gradlew publishToNexus closeAndReleaseRepository --info --stacktrace

notifications:
  slack:
    secure: DD6a5vdzqIVOrSc1meWwHIpYSX3bl4J8eENZiykXylq3XAj74X4DW+AbLcsZY2+Ny2KA6hUIKoQwfJNEtwxUGhNKUlUu3qiGLDm8hzz8JNS44mKQL4zweNdfJFynoo7hFU4bpk+KMgH4WLzxLVMQdVeGIf2XGOio4lJh2XmGf6iNqkuCBDBnQ4WkFk2shx7/zmGacKxDakKOSih+0Ng83HQrKvSwKILeE6KGWIQmmDWN/AiYI6SrqnJs8X20jw9CbnlSYQ1Ak5OTCfMaWHG+/ZcjeqBhFn0TSidohho359LQhfWem6x6PQpN1OrOggyib+9G284oeFXCIbx4Oo5D/CStYIDlOsmlAx45izjCVFtOZmvz59XS8MgN3RIy7VAEIEDh6UGwNWxGyU/vPa/J8c4giIHir2s0Is1TXPWpEOciHOxqQ6sZvHT36DDA/tIluHL1iAvPCgWTrLJV+uHgiMQOQM9KPSK5eUdaBT2dB/8CAlb19snRF6BLfcbvPhs1A1m4j8eloB9pk/DqsjVAVzX2EuD3llvxkTuMY9+NBXsTDbTjgQnJD0BGCinLi3zNCLZIZQvAvFSigTcbIc84MSNnbMXr6OFMV+2AbZGVYMMmic6obCYuToRof++f6bio0UwNvvm0fkmsILUnYVWPr6gMkJCrDywyAA5PF4tOypQ=
env:
  global:
    secure: nDa16Deu7mSK8DSaZHI20Zpm2ZUWIfmIvXwlnExnCEJkvasfz6duTcq/l0XsNgRdQtTDrMwYKm5PPAsNrtakNc9mbP0U4a+8gdIKPVOMbr4QT7jRkfDt9dn+UvbRxSHeDTe0Dgbtsg8SxShyUdzBxdne0c6XTtePNUDVxJUTPt19HAUxYLOWzR6A2nIyNyYvRMoa57sipOCVmXpSSu3yrMdjT0c0IXWp14gyydhl/s3U8qE5iKPr1lr20BNTXq1G12C4mWrX7JtnwOg/Ms/Ol5537A794yGMk7iVdyqBp63o0tz+Mo2PDnZmg5BpPSHGDF9TH92ew63xS/BSYveAkSWy6Uaa5YU5AC19Tyi8a9w4sRy6zNlKMTdH90/JuVn53EhH8ZzeYYBJRoCCvJFatCcU2J8FXFO360bEkn16f5woYH1dSHxnQVdnoQRb5gDr33OAVWBFwAVja2mPkcHsm5VWNVA4t3tjoQ0iFmMdO92wlX/9Hdfei3OCs2Cs+XGLuHOgkO78M6jPZWs063ugO5kzbLHqEWEKsDzgc/r8N7WZNM1OAXs2zCsb0e9RUjPHYM1KWWEwfb7sg/omNpwX9eMql1GIFaGVKS826k54l2fDFlLfwvLdIdHEyiiYQGAzViSeuYgY5hmvh0yJvssx5KTsqUo9SxL1F3OktapNUgQ=
