/*
 * Marketing API v.1.0
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * The version of the OpenAPI document: v.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * AdvertiserQuotaMessage
 */

public class AdvertiserQuotaMessage {
  public static final String SERIALIZED_NAME_ADVERTISER_ID = "advertiserId";
  @SerializedName(SERIALIZED_NAME_ADVERTISER_ID)
  private Integer advertiserId;

  public static final String SERIALIZED_NAME_QUOTA_USED = "quotaUsed";
  @SerializedName(SERIALIZED_NAME_QUOTA_USED)
  private Integer quotaUsed;

  public static final String SERIALIZED_NAME_QUOTA_LIMIT = "quotaLimit";
  @SerializedName(SERIALIZED_NAME_QUOTA_LIMIT)
  private Integer quotaLimit;

  public static final String SERIALIZED_NAME_QUOTA_START_DATE = "quotaStartDate";
  @SerializedName(SERIALIZED_NAME_QUOTA_START_DATE)
  private OffsetDateTime quotaStartDate;

  public static final String SERIALIZED_NAME_QUOTA_END_DATE = "quotaEndDate";
  @SerializedName(SERIALIZED_NAME_QUOTA_END_DATE)
  private OffsetDateTime quotaEndDate;


  public AdvertiserQuotaMessage advertiserId(Integer advertiserId) {
    
    this.advertiserId = advertiserId;
    return this;
  }

   /**
   * Get advertiserId
   * @return advertiserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAdvertiserId() {
    return advertiserId;
  }



  public void setAdvertiserId(Integer advertiserId) {
    this.advertiserId = advertiserId;
  }


  public AdvertiserQuotaMessage quotaUsed(Integer quotaUsed) {
    
    this.quotaUsed = quotaUsed;
    return this;
  }

   /**
   * Get quotaUsed
   * @return quotaUsed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getQuotaUsed() {
    return quotaUsed;
  }



  public void setQuotaUsed(Integer quotaUsed) {
    this.quotaUsed = quotaUsed;
  }


  public AdvertiserQuotaMessage quotaLimit(Integer quotaLimit) {
    
    this.quotaLimit = quotaLimit;
    return this;
  }

   /**
   * Get quotaLimit
   * @return quotaLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getQuotaLimit() {
    return quotaLimit;
  }



  public void setQuotaLimit(Integer quotaLimit) {
    this.quotaLimit = quotaLimit;
  }


  public AdvertiserQuotaMessage quotaStartDate(OffsetDateTime quotaStartDate) {
    
    this.quotaStartDate = quotaStartDate;
    return this;
  }

   /**
   * Get quotaStartDate
   * @return quotaStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getQuotaStartDate() {
    return quotaStartDate;
  }



  public void setQuotaStartDate(OffsetDateTime quotaStartDate) {
    this.quotaStartDate = quotaStartDate;
  }


  public AdvertiserQuotaMessage quotaEndDate(OffsetDateTime quotaEndDate) {
    
    this.quotaEndDate = quotaEndDate;
    return this;
  }

   /**
   * Get quotaEndDate
   * @return quotaEndDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getQuotaEndDate() {
    return quotaEndDate;
  }



  public void setQuotaEndDate(OffsetDateTime quotaEndDate) {
    this.quotaEndDate = quotaEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvertiserQuotaMessage advertiserQuotaMessage = (AdvertiserQuotaMessage) o;
    return Objects.equals(this.advertiserId, advertiserQuotaMessage.advertiserId) &&
        Objects.equals(this.quotaUsed, advertiserQuotaMessage.quotaUsed) &&
        Objects.equals(this.quotaLimit, advertiserQuotaMessage.quotaLimit) &&
        Objects.equals(this.quotaStartDate, advertiserQuotaMessage.quotaStartDate) &&
        Objects.equals(this.quotaEndDate, advertiserQuotaMessage.quotaEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(advertiserId, quotaUsed, quotaLimit, quotaStartDate, quotaEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvertiserQuotaMessage {\n");
    sb.append("    advertiserId: ").append(toIndentedString(advertiserId)).append("\n");
    sb.append("    quotaUsed: ").append(toIndentedString(quotaUsed)).append("\n");
    sb.append("    quotaLimit: ").append(toIndentedString(quotaLimit)).append("\n");
    sb.append("    quotaStartDate: ").append(toIndentedString(quotaStartDate)).append("\n");
    sb.append("    quotaEndDate: ").append(toIndentedString(quotaEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

