/*
 * Marketing API v.1.0
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * The version of the OpenAPI document: v.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.criteo.marketing.model.CategoryBidChangeRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CampaignBidChangeRequest
 */

public class CampaignBidChangeRequest {
  public static final String SERIALIZED_NAME_CAMPAIGN_ID = "campaignId";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID)
  private Integer campaignId;

  public static final String SERIALIZED_NAME_BID_VALUE = "bidValue";
  @SerializedName(SERIALIZED_NAME_BID_VALUE)
  private Double bidValue;

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private List<CategoryBidChangeRequest> categories = null;


  public CampaignBidChangeRequest campaignId(Integer campaignId) {
    
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCampaignId() {
    return campaignId;
  }



  public void setCampaignId(Integer campaignId) {
    this.campaignId = campaignId;
  }


  public CampaignBidChangeRequest bidValue(Double bidValue) {
    
    this.bidValue = bidValue;
    return this;
  }

   /**
   * Get bidValue
   * @return bidValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getBidValue() {
    return bidValue;
  }



  public void setBidValue(Double bidValue) {
    this.bidValue = bidValue;
  }


  public CampaignBidChangeRequest categories(List<CategoryBidChangeRequest> categories) {
    
    this.categories = categories;
    return this;
  }

  public CampaignBidChangeRequest addCategoriesItem(CategoryBidChangeRequest categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CategoryBidChangeRequest> getCategories() {
    return categories;
  }



  public void setCategories(List<CategoryBidChangeRequest> categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignBidChangeRequest campaignBidChangeRequest = (CampaignBidChangeRequest) o;
    return Objects.equals(this.campaignId, campaignBidChangeRequest.campaignId) &&
        Objects.equals(this.bidValue, campaignBidChangeRequest.bidValue) &&
        Objects.equals(this.categories, campaignBidChangeRequest.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignId, bidValue, categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignBidChangeRequest {\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    bidValue: ").append(toIndentedString(bidValue)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

