/*
 * Marketing API v.1.0
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * OpenAPI spec version: v.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CategoryUpdateInput
 */

public class CategoryUpdateInput {
  public static final String SERIALIZED_NAME_CATEGORY_HASH_CODE = "categoryHashCode";
  @SerializedName(SERIALIZED_NAME_CATEGORY_HASH_CODE)
  private Integer categoryHashCode;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public CategoryUpdateInput categoryHashCode(Integer categoryHashCode) {
    this.categoryHashCode = categoryHashCode;
    return this;
  }

   /**
   * Get categoryHashCode
   * @return categoryHashCode
  **/
  @ApiModelProperty(value = "")
  public Integer getCategoryHashCode() {
    return categoryHashCode;
  }

  public void setCategoryHashCode(Integer categoryHashCode) {
    this.categoryHashCode = categoryHashCode;
  }

  public CategoryUpdateInput enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryUpdateInput categoryUpdateInput = (CategoryUpdateInput) o;
    return Objects.equals(this.categoryHashCode, categoryUpdateInput.categoryHashCode) &&
        Objects.equals(this.enabled, categoryUpdateInput.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryHashCode, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryUpdateInput {\n");
    sb.append("    categoryHashCode: ").append(toIndentedString(categoryHashCode)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

