/*
 * Marketing API v.1.0
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * OpenAPI spec version: v.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * SellerCampaignMessage
 */

public class SellerCampaignMessage {
  public static final String SERIALIZED_NAME_SUSPENDED_SINCE = "suspendedSince";
  @SerializedName(SERIALIZED_NAME_SUSPENDED_SINCE)
  private OffsetDateTime suspendedSince;

  public static final String SERIALIZED_NAME_SELLER_ID = "sellerId";
  @SerializedName(SERIALIZED_NAME_SELLER_ID)
  private Long sellerId;

  public static final String SERIALIZED_NAME_CAMPAIGN_ID = "campaignId";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID)
  private Integer campaignId;

  public static final String SERIALIZED_NAME_BID = "bid";
  @SerializedName(SERIALIZED_NAME_BID)
  private Double bid;

  public SellerCampaignMessage suspendedSince(OffsetDateTime suspendedSince) {
    this.suspendedSince = suspendedSince;
    return this;
  }

   /**
   * Get suspendedSince
   * @return suspendedSince
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getSuspendedSince() {
    return suspendedSince;
  }

  public void setSuspendedSince(OffsetDateTime suspendedSince) {
    this.suspendedSince = suspendedSince;
  }

  public SellerCampaignMessage sellerId(Long sellerId) {
    this.sellerId = sellerId;
    return this;
  }

   /**
   * Get sellerId
   * @return sellerId
  **/
  @ApiModelProperty(value = "")
  public Long getSellerId() {
    return sellerId;
  }

  public void setSellerId(Long sellerId) {
    this.sellerId = sellerId;
  }

  public SellerCampaignMessage campaignId(Integer campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @ApiModelProperty(value = "")
  public Integer getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(Integer campaignId) {
    this.campaignId = campaignId;
  }

  public SellerCampaignMessage bid(Double bid) {
    this.bid = bid;
    return this;
  }

   /**
   * Get bid
   * @return bid
  **/
  @ApiModelProperty(value = "")
  public Double getBid() {
    return bid;
  }

  public void setBid(Double bid) {
    this.bid = bid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellerCampaignMessage sellerCampaignMessage = (SellerCampaignMessage) o;
    return Objects.equals(this.suspendedSince, sellerCampaignMessage.suspendedSince) &&
        Objects.equals(this.sellerId, sellerCampaignMessage.sellerId) &&
        Objects.equals(this.campaignId, sellerCampaignMessage.campaignId) &&
        Objects.equals(this.bid, sellerCampaignMessage.bid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suspendedSince, sellerId, campaignId, bid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellerCampaignMessage {\n");
    sb.append("    suspendedSince: ").append(toIndentedString(suspendedSince)).append("\n");
    sb.append("    sellerId: ").append(toIndentedString(sellerId)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    bid: ").append(toIndentedString(bid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

