/*
 * Marketing API v.1.0
 * IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.
 *
 * The version of the OpenAPI document: v.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.criteo.marketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SellerBidInfoMessage
 */

public class SellerBidInfoMessage {
  public static final String SERIALIZED_NAME_SELLER_NAME = "sellerName";
  @SerializedName(SERIALIZED_NAME_SELLER_NAME)
  private String sellerName;

  public static final String SERIALIZED_NAME_BID = "bid";
  @SerializedName(SERIALIZED_NAME_BID)
  private Double bid;


  public SellerBidInfoMessage sellerName(String sellerName) {
    
    this.sellerName = sellerName;
    return this;
  }

   /**
   * Seller name is case insensitive.
   * @return sellerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Seller name is case insensitive.")

  public String getSellerName() {
    return sellerName;
  }



  public void setSellerName(String sellerName) {
    this.sellerName = sellerName;
  }


  public SellerBidInfoMessage bid(Double bid) {
    
    this.bid = bid;
    return this;
  }

   /**
   * New bid.
   * @return bid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "New bid.")

  public Double getBid() {
    return bid;
  }



  public void setBid(Double bid) {
    this.bid = bid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SellerBidInfoMessage sellerBidInfoMessage = (SellerBidInfoMessage) o;
    return Objects.equals(this.sellerName, sellerBidInfoMessage.sellerName) &&
        Objects.equals(this.bid, sellerBidInfoMessage.bid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellerName, bid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SellerBidInfoMessage {\n");
    sb.append("    sellerName: ").append(toIndentedString(sellerName)).append("\n");
    sb.append("    bid: ").append(toIndentedString(bid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

